### ISSUE TITLE
I don't want the cart to be emptied if I click back button. Can u please help me with it.

### ISSUE THREAD

**Issue by Sruthi1498** [xidhu/FoodHunt#6]

**Comment by xidhu** [comment]
Sure. If you want to store cart details forever

1.Delete lines 51,52 in database.kt (It will remove the  clear cart functionality or you can delete all the occurance of cart "delete all" call from the app if you want to use it anywhere else)


![Screenshot from 2021-06-17 12 09 51](https://user-images.githubusercontent.com/64782756/122344959-f2ac7600-cf64-11eb-8e52-661dd0d89d45.png)

2. Add this code in Res_Recl_Adapter.kt line 62 (It will update the proceed button active status)

`if(CartData(context,dummy_ett,"getall").execute().get().toString() != "[]"){
            btn.setText("Proceed To Payment")
            btn.setBackgroundResource(R.color.colorPrimary)
        }else{btn.setBackgroundResource(R.color.grey)
            btn.setText("No items Selected")}`

![Screenshot from 2021-06-17 12 14 13](https://user-images.githubusercontent.com/64782756/122345780-dceb8080-cf65-11eb-8e14-9e85c5b7fd95.png)

I Recommend you to create a new Cart page for listing all the cart items instead of this ,because its inconvenient to add/remove items from different restaurants by opening each restaurant page.

**Comment by Sruthi1498** [comment]
Thank you so much saviour
